import os
import time
# To clear print("\n" * 100) or call on cls()
def cls(): print("\n" * 100)
cls()
time.sleep(1)
#pip-boy image
print("                 ........... ...                    ...........                                      ")
print("                 ............... .........  ....... ........... ....................                 ")
print("                .........  ...   ...   ...   ................. ...   .... ........                   ")
print("              ....       ..................      ............ .........   ....                       ")
print("                              ....                                      .....                        ")
time.sleep(4)
cls()
#
print(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
time.sleep(2)
cls()
print(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
time.sleep(2)
cls()
print(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM")
time.sleep(2)
cls()
print(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM")
time.sleep(2)
cls()
print(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmdddmddddmmmmdmddddmdmmhmhdhhhdhhmddhhhddhdddhhhhhhhhdmmmhmdddhhhhdmNNmmmNMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdhhdhhhhdhdmddhhhhmdhmdNmdddddddNmmmdmmmddmmdhdddhmhhmdmdmdmmmmmmmNMMMMMMMMMMMMMMMMMMM")
time.sleep(2)
cls()
print(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMmmdddmddddmmmmdmddddmdmmhmhdhhhdhhmddhhhddhdddhhhhhhhhdmmmhmdddhhhhdmNNmmmNMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdmdhhdhhhhdhdmddhhhhmdhmdNmdddddddNmmmdmmmddmmdhdddhmhhmdmdmdmmmmmmmNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhhhhhhdddhhhhhhhhdNmNhmhdhhhhhhmddhhhhhhdhhhhhhhhhhhNddhdmmddddhmddmmmMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhNhhhhhhhhhhyhhhyyhhhhNmNhmhddhhyyhmmhdhhhhhyyhhhhyhhhddNNdhhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhdddhyNhdddmmhhhhyhhhNhdhhyyyyyyyyyyyyyhhdNdNdmhhhyyyddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMydyyyyyyyyyyyyhhyyhdNddhdhMdhddddNmddddddddhdmhhyyyyyhNhdhyhhhhyyyyyyyhhhyhMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNhmhhhhhhdhmmdhhhhhhyyyhhhhhyyhyNNmdhdNdddhddmNhddmmddddNhNddhyyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM")
print(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM")
time.sleep(2)
cls()
print("*")
time.sleep(.4)
cls()
print("**")
time.sleep(.4)
cls()
print("***")
time.sleep(.4)
cls()
print("****")
time.sleep(.4)
cls()
print("*****")
time.sleep(.4)
cls()
print("******")
time.sleep(.4)
cls()
print("*******")
time.sleep(.4)
cls()
print("********")
time.sleep(.4)
cls()
print("*********")
time.sleep(.4)
cls()
print("**********")
time.sleep(.4)
cls()
print("**********")
time.sleep(.4)
cls()
print("***********")
time.sleep(.4)
cls()
print("************")
time.sleep(.4)
cls()
print("*************")
time.sleep(.4)
cls()
print("**************")
time.sleep(.4)
cls()
print("***************")
time.sleep(.4)
cls()
print("*************** P")
time.sleep(.4)
cls()
print("*************** PI")
time.sleep(.4)
cls()
print("*************** PIP")
time.sleep(.4)
cls()
print("*************** PIP-")
time.sleep(.4)
cls()
print("*************** PIP-O")
time.sleep(.4)
cls()
print("*************** PIP-OS")
time.sleep(.4)
cls()
print("*************** PIP-OS(")
time.sleep(.4)
cls()
print("*************** PIP-OS(R")
time.sleep(.4)
cls()
print("*************** PIP-OS(R)")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 *")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 **")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ****")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 *****")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ******")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 *******")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 *********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 **********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 *************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 **************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
time.sleep(.4)
cls()
#
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("C")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("CO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COP")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPY")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYR")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRI")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIG")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGH")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 20")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 207")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 R")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 RO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROB")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBC")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("L")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOA")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOAD")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("E")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EX")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXE")
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC V")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VER")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERS")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSI")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSIO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 4")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.1")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("6")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64k R")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RA")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM S")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SY")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYS")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYST")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("3")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("389")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("3891")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 B")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BY")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYT")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES F")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FR")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FRE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("N")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO H")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO H")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOL")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOT")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTA")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAP")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE F")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOU")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUN")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("L")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOA")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD R")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD RO")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1)")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1):")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): D")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DE")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEI")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEIT")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITR")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRI")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 3")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 30")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("****")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*****")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*******")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***********")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("****************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*****************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("******************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*******************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*******************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*******************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("********************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*********************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**********************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***********************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***********************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("****************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*****************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("******************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("******************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("******************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("********************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*******************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("********************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*********************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*********************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**********************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***********************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("****************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*****************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("******************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*******************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("********************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*********************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**********************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("***********************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("************************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("*************************************************")
time.sleep(.4)
cls()
print("*************** PIP-OS(R) V7.1.0.8 ***************")
print("COPYRIGHT 2075 ROBCO(R)")
print("LOADER V1.1")
print("EXEC VERSION 41.10")
print("64K RAM SYSTEM")
print("38911 BYTES FREE")
print("NO HOLOTAPE FOUND")
print("LOAD ROM(1): DEITRIX 303")
print("**************************************************")
time.sleep(.4)
cls()
#OVERSEEER THUMBS UP
time.sleep(2)
print("")                                                      
print("                                               NN N                                                 ")
print("                                             ddhhhh                                                 ")
print("                                             dhhhhhdN                                               ")
print("                                             hhhhhh                                                 ")
print("                                            N hhhh N                                                ")
print("                                         Nddhhhdhhdhd                                               ")
print("                                        dhhhdhhhhhhhhhhN                                            ")
print("                                       NhhhNNhhhhhhhhhhN                                            ")
print("                                        NddddhhhhhhhhdN                                             ")
print("                                          NdddhhhhhhdN                                              ")
print("                                            dhhhdhhh                                                ")
print("                                           Nhhhd hhhN                                               ")
print("                                           dhhhN hhd                                                ")
print("                                           hhdN Ndd N                                               ")
print("                                            N      NN                                               ")
print("")                                                                                           
print("")                                                                                                    
print("                                           INITIATING                                                 ")
time.sleep(4)
cls()
print("")                                                                                                    
print("                                               NN  N                                                ")
print("                                              dhhdhdN                                               ")
print("                                             dhhhhhd                                                ")
print("                                             dhdhhhd                                                ")
print("                                              ddhd N                                                ")
print("                                         N dddddddddd N                                             ")
print("                                        Ndhdddhddhdhdhd                                             ")
print("                                        dhdNNdhhdhdhddhd                                            ")
print("                                        dd   ddddhdddddN                                            ")
print("                                        NddNNdddddddd                                               ")
print("                                         N NNddddddhd                                               ")
print("                                            dhhd hhhd                                               ")
print("                                           Nhhh Nhhh                                                ")
print("                                           dddd NdddN                                               ")
print("                                           ddN   NN                                                 ")
print("")                                                                                                    
print("")                                                                                                   
print("                                           INITIATING                                               ")
time.sleep(2)
cls()
print("")                                                                                                    
print("                                                 N  N                                               ")
print("                                               ddhhhhdN                                             ")
print("                                              NdhhhhhdN                                             ")
print("                                              Nhhhhhhd                                              ")
print("                                              Ndhhhh N                                              ")
print("                                           N dhhhdhddhd                                             ")
print("                                         NdhhhhhhhhhhhhhdN                                          ")
print("                                        Ndhd N hhhdhhhdhh                                           ")
print("                                        dd    Nddddhdddd                                            ")
print("                                       Nd      dddddddd                                             ")
print("                                              dddddddh                                              ")
print("                                             Ndhhd hhh                                              ")
print("                                              hhdN hhdN                                             ")
print("                                            Nddd   dd                                               ")
print("                                            Nd N   N  N                                             ")
print("")                                                                                                    
print("")                                                                                                   
print("                                           INITIATING                                               ")
time.sleep(2)
cls()
print("")
print("                                                 NN                                                 ")
print("                                             N ddddd                                                ")
print("                                             NdhhdhhdN                                              ")
print("                                              hdhhhh                                                ")
print("                                             Ndhhhh N                                               ")
print("                                          N dhhhdhddd N                                             ")
print("                                     dd dhhhhhhhhhhhhhhdN                                           ")
print("                                     d ddddd dhhhhhhhhhhd                                           ")
print("                                              hhhhhdddhd                                            ")
print("                                              hddhhddd                                              ")
print("                                             dddddddh                                               ")
print("                                            Nhhhddhhh                                               ")
print("                                            ddddN hhdN                                              ")
print("                                           Nddd   hh                                                ")
print("                                            ddN  N   N                                              ")
print("                                            N                                                       ")
print("")                                                                                                    
print("")
print("                                           INITIATING                                               ")
time.sleep(2)
cls()
print("")                                                                                                    
print("                                               NN  d N                                              ")
print("                                              Ndddddd                                               ")
print("                                              Ndddddd N                                             ")
print("                                              Ndddddhd                                              ")
print("                                     Nd       Ndddhd N                                              ")
print("                                      dd    dhhhddhddhd N                                           ")
print("                                      dddhhhhhhhhhhhhhhhhd                                          ")
print("                                      N  NNNNNdhhhhhhhhhyhN                                         ")
print("                                              dhhhhhhhdhh                                           ")
print("                                              dhhhhhhhdhN                                           ")
print("                                              dhhhhhhhhN                                            ")
print("                                             Nhhhhdhhhd                                             ")
print("                                             dhhh  hhh                                              ")
print("                                            Ndhhd  hhdN                                             ")
print("                                             dddN NdddN                                             ")
print("                                              N    NNNN                                             ")
print("")                                                                                                    
print("")                                                                                                    
print("                                           INITIATING                                               ")
time.sleep(2)
cls()
print("")                                                                                                    
print("                                               NN    N                                              ")
print("                                                ddddd                                               ")
print("                                        N      dddddd                                               ")
print("                                        NdN     dddddN                                              ")
print("                                        ddd NNN dddd  N                                             ")
print("                                        ddddhhhhhdhdhhhdN                                           ")
print("                                        NNN    hhhhhhhhhh                                           ")
print("                                              NhhhhhhhhhdN                                          ")
print("                                             Nhhhhhhhhd                                             ")
print("                                               hhhhhhh                                              ")
print("                                              dhhhdhhhN                                             ")
print("                                             Nhhh  hhhN                                             ")
print("                                             dhhd  hh                                               ")
print("                                             dd   N   N                                             ")
print("                                             N                                                      ")
print("") 
print("")
print("                                           INITIATING                                                ")
time.sleep(4)








