using System;

class MainClass {
  public static void Main (string[] args) {
Console.ForegroundColor = ConsoleColor.Green;
Console.Title = "Pip-OS v7.1.0.8";
int InfoTime = 500;
Console.WriteLine("                 ........... ...                    ...........                                      ");
Console.WriteLine("                 ............... .........  ....... ........... ....................                 ");
Console.WriteLine("                .........  ...   ...   ...   ................. ...   .... ........                   ");
Console.WriteLine("              ....       ..................      ............ .........   ....                       ");         
Console.WriteLine("                              ....                                      .....                        ");
System.Threading.Thread.Sleep(3000);
Console.Clear();

Console.WriteLine(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");

System.Threading.Thread.Sleep(2000);
Console.Clear();

Console.WriteLine(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");

System.Threading.Thread.Sleep(2000);
Console.Clear();

Console.WriteLine(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM");

System.Threading.Thread.Sleep(2000);
Console.Clear();

Console.WriteLine(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM");

System.Threading.Thread.Sleep(2000);
Console.Clear();

Console.WriteLine(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmdddmddddmmmmdmddddmdmmhmhdhhhdhhmddhhhddhdddhhhhhhhhdmmmhmdddhhhhdmNNmmmNMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdhhdhhhhdhdmddhhhhmdhmdNmdddddddNmmmdmmmddmmdhdddhmhhmdmdmdmmmmmmmNMMMMMMMMMMMMMMMMMMM");

System.Threading.Thread.Sleep(2000);
Console.Clear();

Console.WriteLine(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdddddhhddymdhyyhhhhdNddyhhyhhhhhhhhyhyhydmmmhmddhyyyhhNhhhhhhhhhyyhyyhhhyhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmddddNhhhhddmmhddddhhdhNhNydyyyyhhmdhyhhhhhhhyyhyyyyyyyNdMhNddhhhyhdNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhyyyhhyyhhyyhhyyhNdhhhMmdddddhhmmdddNmdddddddddhhdyhhyyhddNMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyhyhhhyhhhhhhhhhdmdNhNhdhhhyhhmhdhyhhhhhhhyhhhyyyhhNmhhhNddddddmmhmdmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhydmNdddhhhhhhyyhhhhhhhhhmdmdmhdhhhhhhmmhdhhhhhhhhhhhhddhdhmdhhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmdddddmmNdddddmhhhhhhddNhdhhhdhhhhhhhhhhhhdmmdmhmddhhhhhdNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdddhhyddddhddhhhhhmmmNmmdddddddmdddmmdddddmmdddhhhhhdhdmmmmmmmmmdddmdmdmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddhhhhhhhhddhhhhhhmddhddmhhhhdhNmmmmddmdddmNmdddddddNddddmdddhhhhhdmdmmmmMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmNdmddhhhhhhmmhhhhhhhhhhhhdhhhhhhNmddddmdhhddddNddddhhdddNdNmdhhhhhhNMMMNMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhyhhhhhhhhhhhhdNmNhNhdhhhymdNdhyhhhhhhhhyhhhhhhhhNmdhhNmddhdhdddNddmNMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmddddddddhmmhhhhhhydmhhhhyhhyhhhhhhhyhhhdmmNdNhhyyyyhyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhyyyyyhhhhhhhyydNdhhhNdhddddNdhdymhhhyyyhhmmhmhyyyyyhhhhhhhhyhhmNmmmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyyhyhNddhhhhhhhhyyhyyhhhhhNdyyhmmddddddddmhhhhmyyyhyhhhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhhhhhhhhhhhhhhdNmmdNhdhhhhddNdhyyyhyhhyhhhhhhyhhhNdddmmNmdddddmMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmddddddddmdddhhhhhdNhdhhhhhhhhhhhhhhhhhmNmmdmddhhhhhdNhdhhhhhhhhhhhhhhhhhdMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMmmdddmddddmmmmdmddddmdmmhmhdhhhdhhmddhhhddhdddhhhhhhhhdmmmhmdddhhhhdmNNmmmNMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdmdhhdhhhhdhdmddhhhhmdhmdNmdddddddNmmmdmmmddmmdhdddhmhhmdmdmdmmmmmmmNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhhhhhhdddhhhhhhhhdNmNhmhdhhhhhhmddhhhhhhdhhhhhhhhhhhNddhdmmddddhmddmmmMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhNhhhhhhhhhhyhhhyyhhhhNmNhmhddhhyyhmmhdhhhhhyyhhhhyhhhddNNdhhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhdddhyNhdddmmhhhhyhhhNhdhhyyyyyyyyyyyyyhhdNdNdmhhhyyyddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMydyyyyyyyyyyyyhhyyhdNddhdhMdhddddNmddddddddhdmhhyyyyyhNhdhyhhhhyyyyyyyhhhyhMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNhmhhhhhhdhmmdhhhhhhyyyhhhhhyyhyNNmdhdNdddhddmNhddmmddddNhNddhyyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhdhyyyyyyhhyhhhhhyydNddhdmNhhdhhdNhdddhhhddhhNhhhyhhyhNyhyhhyhhhhyyyyyyyyydMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMdNyNhhhhhhhdmdhhhyyyyyyyyyhyhhhhymdddddmmhhddmmNdddddddddMhNddhhyyyhmMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhhhhhhhhhhhhhhhhdMmNdNhdhhhhdhmdddhhhhhhhhhhhhhhhhhNdhdhNmdddmmmdNNmmmmMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddddmmdmddhdmddhhhhhmNdddyhdhhhhhhhhhhhhhmmmmdmhhhhhhddNNNNMNNNNNMNNNMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhddhdhddhhhddhhhhhhhmmhdhmddddddmmhdhdddddddddmmhhhhhhhdmmmmmmmmmdmNNMNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhdhddhhhhhhhdmddhdmdhhddhmddmdmmddddddhddhhhhyhhhhddmmmmmmmmNNNNNMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMddhhhhhhmdhhhhhhhhhhdddhdhhdhmddddmmdhhdddhhmddddmhhhhddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
Console.WriteLine(" MMMMMMMMMMMMhhhhhhhhhhhhhhhhhhhdNmNhNhdhhhhhdmddhhyhhdhhhhhhhhhhhhNmdhdhNdhhhhdmMMMMMMMMMMMMMMMMMMMM");

System.Threading.Thread.Sleep(2000);
Console.Clear();

Console.WriteLine(" *");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" **");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" ***");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" ****");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *****");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" ******");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *******");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" ********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" **********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" ***********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" ************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" **************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" ***************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** P");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PI");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-O");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R)");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 *");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 **");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ****");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 *****");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ******");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 *******");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 *********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 **********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 *************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 **************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.Clear();

Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" C");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" CO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COP");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPY");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYR");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRI");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIG");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGH");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 20");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 207");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 R");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 RO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROB");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBC");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" L");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOA");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOAD");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" E");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EX");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC ");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC V");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VER");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERS");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSI");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSIO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 4");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.1");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 6");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64 ");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K R");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RA");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM S");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SY");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYS");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYST");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 3");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 389");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 3891");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 B");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BY");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYT");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES F");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FR");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FRE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" N");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO H");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOL");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOT");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTA");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAP");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear(); 
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE F");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOU");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUN");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();


Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" L");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOA");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD R");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD RO");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear(); 
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1)");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1):");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): D");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear(); 
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DE");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEI");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEIT");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITR");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRI");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX");
System.Threading.Thread.Sleep(InfoTime); 
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 3");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 30");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();

Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" **");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ***");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ****");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *****");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ******");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *******");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ***********");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ***************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ****************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ******************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *******************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ********************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" **********************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" **************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ****************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ******************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *******************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *********************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" **********************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" **************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ****************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *******************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ********************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *********************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ***********************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" ************************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" *************************************************");
System.Threading.Thread.Sleep(InfoTime);
Console.Clear();
Console.WriteLine(" *************** PIP-OS(R) V7.1.0.8 ***************");
Console.WriteLine(" COPYRIGHT 2075 ROBCO(R)");
Console.WriteLine(" LOADER V1.1");
Console.WriteLine(" EXEC VERSION 41.10");
Console.WriteLine(" 64K RAM SYSTEM");
Console.WriteLine(" 38911 BYTES FREE");
Console.WriteLine(" NO HOLOTAPE FOUND");
Console.WriteLine(" LOAD ROM(1): DEITRIX 303");
Console.WriteLine(" **************************************************");

Console.ReadLine();
}}