import os
import time
import webbrowser
import datetime
# To clear print("\n" * 100) or call on cls()
def cls(): print("\n" * 100)
cls()
#Menu
def menu():
    cls()
    print("What Would You Like To Do? Type the number.")
    print("")
    print("[1]PIP-BOY Info [2]Update [3]Clock [4]STAT [5]INV [6]DATA [7]MAP [8]RADIO [9]EXIT")
    choice=input()
    if choice == "1":
        cls()
        print("*")
        time.sleep(.4)
        cls()
        print("**")
        time.sleep(.4)
        cls()
        print("***")
        time.sleep(.4)
        cls()
        print("****")
        time.sleep(.4)
        cls()
        print("*****")
        time.sleep(.4)
        cls()
        print("******")
        time.sleep(.4)
        cls()
        print("*******")
        time.sleep(.4)
        cls()
        print("********")
        time.sleep(.4)
        cls()
        print("*********")
        time.sleep(.4)
        cls()
        print("**********")
        time.sleep(.4)
        cls()
        print("**********")
        time.sleep(.4)
        cls()
        print("***********")
        time.sleep(.4)
        cls()
        print("************")
        time.sleep(.4)
        cls()
        print("*************")
        time.sleep(.4)
        cls()
        print("**************")
        time.sleep(.4)
        cls()
        print("***************")
        time.sleep(.4)
        cls()
        print("*************** P")
        time.sleep(.4)
        cls()
        print("*************** PI")
        time.sleep(.4)
        cls()
        print("*************** PIP")
        time.sleep(.4)
        cls()
        print("*************** PIP-")
        time.sleep(.4)
        cls()
        print("*************** PIP-O")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R)")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 *")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 **")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ****")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 *****")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ******")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 *******")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 *********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 **********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 *************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 **************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        time.sleep(.4)
        cls()
#
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("C")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("CO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COP")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPY")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYR")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRI")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIG")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGH")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 20")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 207")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 R")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 RO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROB")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBC")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("L")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOA")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOAD")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("E")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EX")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXE")
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC V")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VER")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERS")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSI")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSIO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 4")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.1")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("6")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64k R")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RA")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM S")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SY")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYS")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYST")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("3")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("389")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("3891")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 B")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BY")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYT")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES F")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FR")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FRE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("N")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO H")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO H")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOL")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOT")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTA")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAP")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE F")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOU")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUN")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("L")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOA")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD R")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD RO")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1)")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1):")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): D")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DE")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEI")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEIT")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITR")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRI")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 3")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 30")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("****")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*****")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*******")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***********")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("****************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*****************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("******************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*******************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*******************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*******************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("********************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*********************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**********************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***********************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***********************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("****************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*****************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("******************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("******************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("******************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("********************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*******************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("********************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*********************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*********************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**********************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***********************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("****************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*****************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("******************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*******************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("********************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*********************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**********************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("***********************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("************************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("*************************************************")
        time.sleep(.4)
        cls()
        print("*************** PIP-OS(R) V7.1.0.8 ***************")
        print("COPYRIGHT 2075 ROBCO(R)")
        print("LOADER V1.1")
        print("EXEC VERSION 41.10")
        print("64K RAM SYSTEM")
        print("38911 BYTES FREE")
        print("NO HOLOTAPE FOUND")
        print("LOAD ROM(1): DEITRIX 303")
        print("**************************************************")
        time.sleep(2)
        print("Wanna check for update?")
        print("  1. to check for update")
        print("  2. Menu")
        want_update = input("Enter answer:")
        if want_update == "1":
            cls()
            print("Checking for new version /Update.............")
            print("")
            input("Press Enter to continue...")
            cls()
            webbrowser.open('https://github.com/PiSaucer/PIP-OS-R-V7.1.0.8/releases')
            print("no update available,Try Againg after some time.")
            print("")
            input("Press Enter to continue...")
            time.sleep(5)
            cls()
            menu()
        else:
            print("Please Wait")
            time.sleep(3)
            cls()
            menu()
    if choice == "2":
        cls()
        print("Checking for new version /Update.............")
        print("")
        input("Press Enter to continue...")
        cls()
        webbrowser.open('https://github.com/PiSaucer/PIP-OS-R-V7.1.0.8/releases')
        print("no update available,Try Againg after some time.")
        print("")
        input("Press Enter to continue...")
        time.sleep(5)
        cls()
        menu()
    if choice == "3":
        cls()
        now = datetime.datetime.now()
        print("The current time is:")
        print (now.strftime("%H:%M:%S"))
        input("Press Enter to continue...")
        time.sleep(5)
        cls()
        menu()
    if choice == "4":
        cls()
        print("not ready yet")
        time.sleep(5)
        cls()
        menu()
    if choice == "5":
        cls()
        print("not ready yet")
        time.sleep(5)
        cls()
        menu()
    if choice == "6":
        cls()
        print("not ready yet")
        time.sleep(5)
        cls()
        menu()
    if choice == "7":
        cls()
        print("not ready yet")
        time.sleep(5)
        cls()
        menu()
    if choice == "8":
        cls()
        print("Diamond City Radio")
        webbrowser.open('https://www.youtube.com/playlist?list=PL_dZzj4H0GQKP--78TbXjzrLvctheSFQw')
        input("Press Enter to continue...")
        time.sleep(5)
        cls()
        menu()
    if choice == "9":
        cls()
        print("Are you sure you want to EXIT?")
        print("(y/n)")
        want_exit = input("EXIT:")
        if want_exit == "y":
            print("good bye")
            print("please wait")
            time.sleep(3)
            exit()
        else:
            print("please wait")
            time.sleep(3)
            cls()
            menu()
    if choice == "pisaucer":
        cls()
        print("this was made by PiSaucer.")
        print("PS DON'T TELL ANY ONE!!! ;) ")
        print("")
        input("Press Enter to continue...")
        cls()
        menu()
print("loading ...")
time.sleep(3)
cls()
menu()

