var lyrics = [{
    delay: "2.00",
    text: "Forms FORM-29827281-12:",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.00",
    text: "Test Assessment Report",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.01",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.01",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.85",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.05",
    text: "This was a triumph.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.9",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.1",
    text: "I'm making a note here:",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.1",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.8",
    text: "HUGE SUCCESS.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.00",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.36",
    text: "It's hard to overstate",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.04",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.71",
    text: "my satisfaction.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.13",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.76",
    text: "Aperture Science",
    nonewline: 0,
    clear: 0,
    changepicture: 1
}, {
    delay: "2.10",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.57",
    text: "We do what we must",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.20",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.75",
    text: "because",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.1",
    text: " ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.71",
    text: "we can.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.67",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.55",
    text: "For the good",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.53",
    text: " of all of us.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.279",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.741",
    text: "Except the ones who are dead.",
    nonewline: 0,
    clear: 0,
    changepicture: 6
}, {
    delay: "0.400",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.858",
    text: "But there's no sense crying",
    nonewline: 0,
    clear: 0,
    changepicture: 1
}, {
    delay: "0.01",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.782",
    text: "over every mistake.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.200",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.985",
    text: "You just keep on trying",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.01",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.366",
    text: "till you run out of",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.400",
    text: " cake.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.186",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.97",
    text: "And the Science gets done.",
    nonewline: 0,
    clear: 0,
    changepicture: 5
}, {
    delay: "1.97",
    text: "And you make a neat gun.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.02",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.52",
    text: "For the people who are",
    nonewline: 0,
    clear: 0,
    changepicture: 1
}, {
    delay: "0.02",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.50",
    text: "still alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.5",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.1",
    text: "",
    nonewline: 0,
    clear: 1,
    changepicture: -1
}, {
    delay: "0.55",
    text: "Forms FORM-55551-5:",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.10",
    text: "Personnel File Addendum:",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.66",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.35",
    text: "Dear <<Subject Name Here>>,",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.06",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.917",
    text: "I'm not even angry.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.368",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.697",
    text: "I'm being ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.65",
    text: "so",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.906",
    text: " sincere ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.115",
    text: "right now.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.625",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.65",
    text: "Even ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.347",
    text: "though you ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.488",
    text: "broke ",
    nonewline: 1,
    clear: 0,
    changepicture: 8
}, {
    delay: "0.998",
    text: "my heart.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.325",
    text: "And ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.488",
    text: "killed ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.557",
    text: "me.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.00",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.649",
    text: "And tore me to pieces.",
    nonewline: 0,
    clear: 0,
    changepicture: 3
}, {
    delay: "2.322",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.440",
    text: "And threw every piece",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.302",
    text: " ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.580",
    text: "into",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.395",
    text: " ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.882",
    text: "a fire.",
    nonewline: 0,
    clear: 0,
    changepicture: 11
}, {
    delay: "1.649",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.400",
    text: "As they burned ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.509",
    text: "it hurt because",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.325",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.625",
    text: "I was so happy for you!",
    nonewline: 0,
    clear: 0,
    changepicture: 9
}, {
    delay: "0.441",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.067",
    text: "Now these points of data",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.950",
    text: "make a beautiful line.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.020",
    text: "And we're out of beta.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.950",
    text: "We're releasing on time.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.113",
    text: "So I'm GLaD. I got burned.",
    nonewline: 0,
    clear: 0,
    changepicture: 3
}, {
    delay: "2.020",
    text: "Think of all the things we learned",
    nonewline: 0,
    clear: 0,
    changepicture: 5
}, {
    delay: "1.556",
    text: "for the people who are",
    nonewline: 0,
    clear: 0,
    changepicture: 1
}, {
    delay: "0.395",
    text: "still",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.440",
    text: " alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.5",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.1",
    text: "",
    nonewline: 0,
    clear: 1,
    changepicture: -1
}, {
    delay: "0.45",
    text: "Forms FORM-55551-6:",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.31",
    text: "Personnel File Addendum Addendum:",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.66",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.20",
    text: "One last thing:",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.05",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.324",
    text: "Go ahead and leave ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.627",
    text: "me.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.788",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.534",
    text: "I think ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.184",
    text: "I prefer ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.022",
    text: "to stay ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.232",
    text: "in",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.882",
    text: "side.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.43",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.511",
    text: "May",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.972",
    text: "be you'll find someone else",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.254",
    text: "to help you.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.252",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.511",
    text: "Maybe ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.325",
    text: "Black ",
    nonewline: 1,
    clear: 0,
    changepicture: 7
}, {
    delay: "0.998",
    text: "Mesa",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.183",
    text: "... ",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.440",
    text: "THAT WAS A JOKE.",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.021",
    text: " ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.279",
    text: "FAT ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.859",
    text: "CHANCE.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.393",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.486",
    text: "Anyway",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.765",
    text: ", this cake is great.",
    nonewline: 0,
    clear: 0,
    changepicture: 2
}, {
    delay: "1.904",
    text: "It's so delicious and moist.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.418",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.927",
    text: "Look at me still talking",
    nonewline: 0,
    clear: 0,
    changepicture: 12
}, {
    delay: "2.090",
    text: "when there's Science to do.",
    nonewline: 0,
    clear: 0,
    changepicture: 6
}, {
    delay: "1.695",
    text: "When I look out there,",
    nonewline: 0,
    clear: 0,
    changepicture: 1
}, {
    delay: "2.183",
    text: "it makes me GLaD I'm not you.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "2.043",
    text: "I've experiments to run.",
    nonewline: 0,
    clear: 0,
    changepicture: 5
}, {
    delay: "2.020",
    text: "There is research to be done.",
    nonewline: 0,
    clear: 0,
    changepicture: 3
}, {
    delay: "1.625",
    text: "On the people who are",
    nonewline: 0,
    clear: 0,
    changepicture: 1
}, {
    delay: "0.348",
    text: "still ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.440",
    text: "alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.2",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.01",
    text: "",
    nonewline: 0,
    clear: 1,
    changepicture: -1
}, {
    delay: "0.10",
    text: "",
    nonewline: 0,
    clear: 1,
    changepicture: -1
}, {
    delay: "0.01",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.01",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.01",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.3",
    text: "PS: ",
    nonewline: 1,
    clear: 0,
    changepicture: 0
}, {
    delay: "1.625",
    text: "And believe me I am",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.138",
    text: "still alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.8",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.198",
    text: "PPS: ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.904",
    text: "I'm doing Science and I'm",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.091",
    text: "still alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.8",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.175",
    text: "PPPS: ",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.904",
    text: "I feel FANTASTIC and I'm",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.091",
    text: "still alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.1",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.154",
    text: "FINAL THOUGHT: ",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.579",
    text: "While you're dying I'll be",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.254",
    text: "still alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.1",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.829",
    text: "FINAL THOUGHT PS: ",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.834",
    text: "And when you're dead I will be",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.161",
    text: "still alive.",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.459",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.400",
    text: "",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "1.184",
    text: "STILL ALIVE",
    nonewline: 0,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.2",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.1",
    text: "",
    nonewline: 0,
    clear: 1,
    changepicture: -1
}, {
    delay: "45.279",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}, {
    delay: "0.279",
    text: "",
    nonewline: 1,
    clear: 0,
    changepicture: -1
}];
